name: OSS Governance

on:
  push:
    branches: [main]
    paths: [.github/labels.yml, .github/workflows/oss-governance-labels.yml]

permissions:
  contents: read
  issues: write

jobs:
  main:
    name: Governance Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
