name: OSS

on:
  push:
    branches: [main]
    paths: [.github/labels.yml, .github/workflows/oss-governance-labels.yml]

permissions:
  contents: read
  issues: write

jobs:
  main:
    name: Governance Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
